In [1]:
import numpy as np

In [2]:
arr=np.arange(1000000)

In [3]:
pylist=list(range(1000000))

In [4]:
%time for _ in range(10):[item*3 for item in pylist]

CPU times: user 506 ms, sys: 75.7 ms, total: 582 ms
Wall time: 581 ms


In [5]:
%time for _ in range(10): arr=arr*3

CPU times: user 22 ms, sys: 4.32 ms, total: 26.4 ms
Wall time: 25.3 ms


In [6]:
np.array=[12,34,56,23,546]

In [7]:
print(np.array)

[12, 34, 56, 23, 546]


# numpy tutorial

In [8]:
import numpy as np

In [10]:
myarr = np.array([[12,13,53,6]], np.int8) 
#python objects se numpy array

In [11]:
myarr

array([[12, 13, 53,  6]], dtype=int8)

In [12]:
myarr[0]

array([12, 13, 53,  6], dtype=int8)

In [13]:
myarr[0,1]

13

In [14]:
myarr.shape

(1, 4)

In [15]:
myarr.dtype

dtype('int8')

**Numpy Types Reference**

In [16]:
myarr[0,0]=23

In [17]:
myarr

array([[23, 13, 53,  6]], dtype=int8)

# Array Creation: conversion from other Python Structures

In [18]:
listarray= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
listarray.size

9

In [21]:
listarray.dtype

dtype('int64')

In [22]:
listarray.shape

(3, 3)

In [23]:
np.array({32,33,45})

array({32, 33, 45}, dtype=object)

# Intrinsic Numpy Array Creation

In [24]:
zeros= np.zeros((2,3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
rng = np.arange(15) 
#numpy array bna k dega

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
 lspace = np.linspace(1,5,12)
    #equally linearly spaced elements in array

In [29]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [30]:
ls2 = np.linspace(1,100,4)

In [31]:
ls2

array([  1.,  34.,  67., 100.])

In [32]:
import numpy as np
emp = np.empty((4,6))

In [33]:
emp

array([[4.64709855e-310, 0.00000000e+000, 1.33360303e+241,
        8.71588551e-310, 1.40771468e-147, 7.09708124e-313],
       [5.40840706e-308, 6.21822213e+175, 2.63920065e-314,
        4.02977151e-270, 2.93571719e-135, 1.37251951e-231],
       [2.44308331e-289, 6.27969305e-299, 4.78064292e-299,
        4.78064292e-299, 5.07928728e-299, 1.10353068e-279],
       [6.40456758e-279, 2.68515865e-229, 1.04802865e-279,
        1.92711228e-239, 1.10396277e-279, 7.43024643e-251]])

In [34]:
emp_like = np.empty_like(ls2)

In [35]:
emp_like

array([  1.,  34.,  67., 100.])

In [36]:
ide = np.identity(5)

In [37]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
ide.shape

(5, 5)

In [39]:
arr = np.arange(99)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
ide.size

25

In [44]:
import numpy as np
x=[[1,2,3],[4,5,6],[7,8,9]]

In [45]:
arr= np.array(x)

# numpy attributes

In [46]:
import numpy as np

In [47]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [48]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
arr.flat

In [50]:
for items in arr.flat:
    print(items)

1
2
3
4
5
6
7
8
9


In [51]:
arr.ndim
#number of dimensions

2

In [53]:
arr.nbytes 
#bytes required to store the data

72

In [54]:
one= np.array([1,2,3,45,66])

In [55]:
one.argmax()
#index of max element

4

In [56]:
one.argmin()
#index of min element

0

In [57]:
one.argsort()
#give the index of elements in accending order

array([0, 1, 2, 3, 4])

In [58]:
two = np.array([2,34,24,13,1])

In [59]:
two.argsort()

array([4, 0, 3, 2, 1])

In [64]:
ary= np.array([[1,2,3],
              [4,15,6],
              [7,0,9]])

In [65]:
ary.argmin()

7

In [66]:
ary.argmax()

4

In [67]:
ary.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [1, 0, 2]])

In [68]:
ary.argmax(axis=0)

array([2, 1, 2])

In [69]:
ary.argsort(axis=1)

array([[0, 1, 2],
       [0, 2, 1],
       [1, 0, 2]])

In [71]:
ary.ravel()

array([ 1,  2,  3,  4, 15,  6,  7,  0,  9])

In [73]:
ary.reshape(1,9)

array([[ 1,  2,  3,  4, 15,  6,  7,  0,  9]])








# matrix // mathematical calculations using numpy

In [74]:
ary2 = np.array([[3,2,1],
                [6,5,4],
                [9,8,7]])

In [75]:
ary + ary2

array([[ 4,  4,  4],
       [10, 20, 10],
       [16,  8, 16]])

In [76]:
[23 ,442] + [42,34]

[23, 442, 42, 34]

In [78]:
np.sqrt(ary2)

array([[1.73205081, 1.41421356, 1.        ],
       [2.44948974, 2.23606798, 2.        ],
       [3.        , 2.82842712, 2.64575131]])

In [79]:
ary2.sum()

45

In [80]:
ary2.max()

9

In [81]:
ary2.min()

1

In [82]:
ary2

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [84]:
np.where(ary2>6)

(array([2, 2, 2]), array([0, 1, 2]))

In [85]:
type(np.where(ary2>6))

tuple

In [86]:
np.count_nonzero(ary2)

9

In [87]:
np.nonzero(ary2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [89]:
ary2[1,2]=0

In [90]:
np.nonzero(ary2)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [91]:
import sys

In [92]:
py_ar = [0,3,24]

In [93]:
np_ar = np.array(py_ar)

In [94]:
sys.getsizeof(1)*len(py_ar)

84

In [99]:
np_ar.itemsize * np_ar.size

24

**numpy array atributes doc**

**docs.scipy.orgs**
