In [1]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


# SVM Classifier

In [3]:
from sklearn import svm
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [5]:
type(iris)

sklearn.utils.Bunch

In [6]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
iris.target
#0 for setosa
#1 for virginica
#2 for versicolor

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
 x= iris.data[:,2]
    #independent variable

In [11]:
y= iris.target
#dependent variable

In [12]:
from sklearn.model_selection import train_test_split
import numpy as np

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=4)

In [14]:
x_train_mod= x_train.reshape(-1,1)

In [15]:
x_test_mod= x_test.reshape(-1,1)

In [16]:
y_train_mod= y_train.reshape(-1,1)

In [17]:
y_test_mod= y_test.reshape(-1,1)

In [18]:
model= svm.SVC(kernel='linear')

In [19]:
model.fit(x_train.reshape(-1,1),y_train.reshape(-1,1))

/home/ishi/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='linear')

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
y_pred_mod = model.predict(x_test_mod)

In [22]:
print(accuracy_score(y_test_mod,y_pred_mod))

0.9666666666666667


# K nearest neighbours (KNN)


In [23]:
from sklearn.datasets import load_iris
iris = load_iris()

In [24]:
x= iris.data
y= iris.target

In [25]:
x.shape

(150, 4)

In [26]:
y.shape

(150,)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
knn= KNeighborsClassifier(n_neighbors=4)

In [29]:
knn

KNeighborsClassifier(n_neighbors=4)

In [30]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=4)

In [31]:
import numpy as np
a= np.array([4,5,6,7])

In [32]:
a.shape

(4,)

In [33]:
knn.predict([a])

array([2])

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
logreg=LogisticRegression()
logreg.fit(x,y)
logreg.predict([a])

/home/ishi/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([2])